import OperatingDT as OperatingDT

OperatingDT.DELETE_PLANOGRAMS()
OperatingDT.DELETE_PRODUCT_GTINS()
OperatingDT.DELETE_PRODUCT_UNITS()
OperatingDT.DELETE_PRODUCTDESCS()
OperatingDT.DELETE_PRODUCTS()
